// Generated by gencpp from file multi_motor/Control.msg
// DO NOT EDIT!


#ifndef MULTI_MOTOR_MESSAGE_CONTROL_H
#define MULTI_MOTOR_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_motor
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : id(0)
    , position(0)
    , speed(0)
    , torque(0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)
    , speed(0)
    , torque(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint16_t _position_type;
  _position_type position;

   typedef uint16_t _speed_type;
  _speed_type speed;

   typedef uint16_t _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::multi_motor::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_motor::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::multi_motor::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::multi_motor::Control > ControlPtr;
typedef boost::shared_ptr< ::multi_motor::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_motor::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_motor::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_motor::Control_<ContainerAllocator1> & lhs, const ::multi_motor::Control_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.speed == rhs.speed &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_motor::Control_<ContainerAllocator1> & lhs, const ::multi_motor::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_motor::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_motor::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_motor::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_motor::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_motor::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_motor::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_motor::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "122d3d32ebb831b360ed3f4fa0e1d17b";
  }

  static const char* value(const ::multi_motor::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x122d3d32ebb831b3ULL;
  static const uint64_t static_value2 = 0x60ed3f4fa0e1d17bULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_motor::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_motor/Control";
  }

  static const char* value(const ::multi_motor::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_motor::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint16 position\n"
"uint16 speed\n"
"uint16 torque\n"
;
  }

  static const char* value(const ::multi_motor::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_motor::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.speed);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_motor::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_motor::Control_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
    s << indent << "speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.speed);
    s << indent << "torque: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MOTOR_MESSAGE_CONTROL_H
