// Generated by gencpp from file multi_motor/GetPosition.msg
// DO NOT EDIT!


#ifndef MULTI_MOTOR_MESSAGE_GETPOSITION_H
#define MULTI_MOTOR_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <multi_motor/GetPositionRequest.h>
#include <multi_motor/GetPositionResponse.h>


namespace multi_motor
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace multi_motor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_motor::GetPosition > {
  static const char* value()
  {
    return "fa82be1deaeed2877bd58e858d4dcf23";
  }

  static const char* value(const ::multi_motor::GetPosition&) { return value(); }
};

template<>
struct DataType< ::multi_motor::GetPosition > {
  static const char* value()
  {
    return "multi_motor/GetPosition";
  }

  static const char* value(const ::multi_motor::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::multi_motor::GetPositionRequest> should match
// service_traits::MD5Sum< ::multi_motor::GetPosition >
template<>
struct MD5Sum< ::multi_motor::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_motor::GetPosition >::value();
  }
  static const char* value(const ::multi_motor::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_motor::GetPositionRequest> should match
// service_traits::DataType< ::multi_motor::GetPosition >
template<>
struct DataType< ::multi_motor::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::multi_motor::GetPosition >::value();
  }
  static const char* value(const ::multi_motor::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_motor::GetPositionResponse> should match
// service_traits::MD5Sum< ::multi_motor::GetPosition >
template<>
struct MD5Sum< ::multi_motor::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_motor::GetPosition >::value();
  }
  static const char* value(const ::multi_motor::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_motor::GetPositionResponse> should match
// service_traits::DataType< ::multi_motor::GetPosition >
template<>
struct DataType< ::multi_motor::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::multi_motor::GetPosition >::value();
  }
  static const char* value(const ::multi_motor::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_MOTOR_MESSAGE_GETPOSITION_H
