// Generated by gencpp from file single_motor/GetPositionResponse.msg
// DO NOT EDIT!


#ifndef SINGLE_MOTOR_MESSAGE_GETPOSITIONRESPONSE_H
#define SINGLE_MOTOR_MESSAGE_GETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace single_motor
{
template <class ContainerAllocator>
struct GetPositionResponse_
{
  typedef GetPositionResponse_<ContainerAllocator> Type;

  GetPositionResponse_()
    : position(0)  {
    }
  GetPositionResponse_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef uint16_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::single_motor::GetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::single_motor::GetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionResponse_

typedef ::single_motor::GetPositionResponse_<std::allocator<void> > GetPositionResponse;

typedef boost::shared_ptr< ::single_motor::GetPositionResponse > GetPositionResponsePtr;
typedef boost::shared_ptr< ::single_motor::GetPositionResponse const> GetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::single_motor::GetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::single_motor::GetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::single_motor::GetPositionResponse_<ContainerAllocator1> & lhs, const ::single_motor::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::single_motor::GetPositionResponse_<ContainerAllocator1> & lhs, const ::single_motor::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace single_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::single_motor::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::single_motor::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::single_motor::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::single_motor::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::single_motor::GetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::single_motor::GetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::single_motor::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6fa9d1b49571c7fff8bae5e451e5e59";
  }

  static const char* value(const ::single_motor::GetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6fa9d1b49571c7fULL;
  static const uint64_t static_value2 = 0xff8bae5e451e5e59ULL;
};

template<class ContainerAllocator>
struct DataType< ::single_motor::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "single_motor/GetPositionResponse";
  }

  static const char* value(const ::single_motor::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::single_motor::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 position\n"
"\n"
;
  }

  static const char* value(const ::single_motor::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::single_motor::GetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::single_motor::GetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::single_motor::GetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINGLE_MOTOR_MESSAGE_GETPOSITIONRESPONSE_H
