from Servo_Control import *

#ping()
# # start()
# # stop()
# gui_torque_input()
# read_position()
# gui_input()
# read_position()
# time.sleep(5)
# input_position(2048)
# time.sleep(5)
# input_position(1024)
# time.sleep(5)
# input_position(0)
# time.sleep(5)
# read_position()
ping()